name: CI Build

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'

jobs:
  Build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    services:
      postgres:
        image: postgres:alpine
        ports:
        - 5432:5432
        env:
          POSTGRES_DB: testdb
          POSTGRES_PASSWORD: pgs3cr3t
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 15s
          --health-timeout 5s
          --health-retries 3
        
    steps:
    - name: Install PostgreSQL client
      run: apt-get update && apt-get install -y postgresql-client

    - name: Wait for DB
      run: |
        until pg_isready -h postgres -p 5432 -U postgres; do
        echo "Waiting for postgres..."
        sleep 2
        done

    - name: checkout
      uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt

    - name: lint test with flake8
      run: |
        flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
    
    - name: unit tests
      run: nosetests --with-spec --spec-color --with-coverage --cover-package=service
      env:
        POSTGRES_URI: "postgresql://postgres:pgs3cr3t@postgres:5432/testdb"
    