name: CI Build

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'

jobs:
  Build:
    runs-on: ubuntu-latest
    container: python:3.9-slim   
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt

    - name: lint test with flake8
      run: |
        flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
    
    - name: unit tests
      run: nosetests --with-spec --spec-color --with-coverage --cover-package=service
    
    
